### ISSUE TITLE
thought : can I do word of the day card ? 

### ISSUE THREAD

**Issue by rohitroy-github** [akanshSirohi/Github-Cards-API#27]
Sample data : 
{
        "index": 0,
        "word": "abate",
        "meaning": "to become less intense or widespread"
    },
    {
        "index": 1,
        "word": "acerbic",
        "meaning": "sharp and forthright in speech or manner"
    },
    {
        "index": 2,
        "word": "benevolent",
        "meaning": "well-meaning and kindly"
    },
    {
        "index": 3,
        "word": "candor",
        "meaning": "the quality of being open and honest"
    },
    {
        "index": 4,
        "word": "deleterious",
        "meaning": "causing harm or damage"
    },
    {
        "index": 5,
        "word": "ephemeral",
        "meaning": "lasting for a very short time"
    },

**Comment by akanshSirohi** [comment]
Sure you can start
