### ISSUE TITLE
thought : I have a few more new card ideas to implement ! 

### ISSUE THREAD

**Issue by rohitroy-github** [akanshSirohi/Github-Cards-API#29]
@akanshSirohi Can I add them once I finish finalising?

**Comment by akanshSirohi** [comment]
Create new issue for each new implementation, also the branch name should be appropriate to your feature.
Example: For adding new card, branch name should be `new-card-card_name`
Also the data file should contain more than 100 or 200 entries.

**Comment by Anniebhalla10** [comment]
@rohitroy-github @rohitroy-github  im having trouble running the project in localhost. Could you help me?

**Comment by akanshSirohi** [comment]
@Anniebhalla10 What issues you were facing..?
