### ISSUE TITLE
[idea] Security Tip Card

### ISSUE THREAD

**Issue by alexwastaken** [akanshSirohi/Github-Cards-API#82]
"Security Tip Card" – Provides daily security tips to help developers write safer code and understand security best practices.

**Comment by alexwastaken** [comment]
Please assign this to me

**Comment by akanshSirohi** [comment]
@alexwastaken Gentle reminder: It has been three days since you opened this issue. Please submit a PR, or I will have to close it.

**Comment by alexwastaken** [comment]
working on it now
