### ISSUE TITLE
[idea]Team Messaging Game Card

### ISSUE THREAD

**Issue by gpatchikoru** [akanshSirohi/Github-Cards-API#84]
Sending updates about a project
Requesting feedback
Informing the team about upcoming deadlines
Communicating issues or blockers
Welcoming a new team member
add on more messages send as a professional way if you are team member.

please assign me this task

**Comment by akanshSirohi** [comment]
@gpatchikoru I don't think this idea suits the project, as the project's sole purpose is to display static cards. We can't include any interactive cards. Please check other cards to get the idea.
