### ISSUE TITLE
Health Tip Card

### ISSUE THREAD

**Issue by Nayanika1402** [akanshSirohi/Github-Cards-API#97]
It is designed to provide users with daily health-related tips to encourage wellness and healthy habits.

**Comment by akanshSirohi** [comment]
@Nayanika1402 Do you want me to assign this to you..?

**Comment by akanshSirohi** [comment]
@Nayanika1402 Please add the PR for your card or I have to close this issue.

**Comment by Nayanika1402** [comment]
@akanshSirohi I will submit it by tomorrow.
